name: Build and Push to ECR

# This file defines one job called build_scan. It runs when code is pushed to the main branch.

on:
  push:
    # Pull_request:
    #     branches: ['main', 'dev']
    branches: ["main"]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          format: "HIGH, CRITICAL"
          exit-code: "1"

      - name: Build Docker image
        run: docker build -t 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0
        with:
          image-ref: 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::995603457526:role/github-action-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to Amazon ECR
        run: |
          docker tag 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          docker push 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
