name: Build and Push to ECR

on:
  push:
    # pull_requests:
    #     branches: ['main', 'dev']
    branches: ["main"]

# Giving the workflow permissions to access the repository and perform actions on it.

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write

# Declaring the Jobs to be run in the workflow
jobs:
  build_scan: #
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps: #Where we start to declare the steps to be run in the job.
      - name: Checkout Code
        uses: actions/checkout@v7 # Code that tells the workflow to checkout(downloading and cloning ) the code from the repository.

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          severity: CRITICAL,HIGH
          exit-code: 1

      # Onother step
      - name: Build Docker Image
        run: docker build -t 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .

        #After building the docker image we now need to scan the image for vulnerabilities using Trivy.
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: table
          scan-type: "image"
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::995603457526:role/github-action-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to Amazon ECR
        run: docker push 995603457526.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
