name: My first pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest # macos-latest, windows-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t valen1/cicd-portfolio .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: valen1
          password: ${{ secrets.DOCKER_PASS }}
          name: Push image
          run: docker push valen1/cicd-portfolio
